spring:
  datasource:
    url: ${JDBC_DATABASE_URL:${DATABASE_URL}}
    username: ${JDBC_DATABASE_USERNAME:${DB_USER:}}
    password: ${JDBC_DATABASE_PASSWORD:${DB_PASS:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
